version: '3'
services:
  application:
    container_name: havana_web
    image: dangminhtruong/havana_api:latest
    ports:
     - "3000:3000"
    volumes:
     - .:/app
    depends_on:
     - mongodb
  mongodb:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - 27017:27017
    volumes:
     - .docker/mogodb:/var/lib/mongodb
