build:
  phpunit:
    image: dangminhtruong/havana_api:latest
    commands:
    - npm install
    - eslint routes
    - cd database/seeder
    - node category_seeder
    - node product_seeder
    - node user_seeder
services:
  mongodb:
    image: mongo
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  docker:
    username: octocat
    password: password
    email: xdangminhtruongx@gmail.com
